CREATE TABLE "follows" (
  "following_user_id" integer NOT NULL,
  "followed_user_id" integer NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()'
);

CREATE TABLE "users" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "username" varchar,
  "email" varchar NOT NULL,
  "profile_picture" varchar,
  "bio" varchar,
  "role" varchar NOT NULL,
  "last_activity_at" timestamp NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()'
);

CREATE TABLE "posts" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "title" varchar,
  "body" text,
  "user_id" integer NOT NULL,
  "status" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()'
);

CREATE TABLE "messages" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "sender_user_id" integer NOT NULL,
  "receiver_user_id" integer NOT NULL,
  "text" text,
  "created_at" timestamp NOT NULL DEFAULT 'now()',
  "status" varchar NOT NULL
);

CREATE TABLE "chat_rooms" (
  "id" INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar NOT NULL,
  "created_at" timestamp NOT NULL DEFAULT 'now()'
);

CREATE TABLE "chat_room_participants" (
  "chat_room_id" integer NOT NULL,
  "user_id" integer NOT NULL
);

CREATE TABLE "read_receipts" (
  "message_id" integer NOT NULL,
  "user_id" integer NOT NULL,
  "read_at" timestamp NOT NULL DEFAULT 'now()'
);

COMMENT ON COLUMN "posts"."body" IS 'Content of the post';

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("following_user_id") REFERENCES "users" ("id");

ALTER TABLE "follows" ADD FOREIGN KEY ("followed_user_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("sender_user_id") REFERENCES "users" ("id");

ALTER TABLE "messages" ADD FOREIGN KEY ("receiver_user_id") REFERENCES "users" ("id");

ALTER TABLE "chat_room_participants" ADD FOREIGN KEY ("chat_room_id") REFERENCES "chat_rooms" ("id");

ALTER TABLE "chat_room_participants" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "read_receipts" ADD FOREIGN KEY ("message_id") REFERENCES "messages" ("id");

ALTER TABLE "read_receipts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
