// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0
// source: account.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createAccount = `-- name: CreateAccount :one
INSERT INTO users (
username,
email,
profile_picture,
bio,
role,
last_activity_at
) VALUES (
$1, $2, $3, $4, $5, $6
) RETURNING id, username, email, profile_picture, bio, role, last_activity_at, created_at
`

type CreateAccountParams struct {
	Username       sql.NullString `json:"username"`
	Email          string         `json:"email"`
	ProfilePicture sql.NullString `json:"profile_picture"`
	Bio            sql.NullString `json:"bio"`
	Role           string         `json:"role"`
	LastActivityAt time.Time      `json:"last_activity_at"`
}

func (q *Queries) CreateAccount(ctx context.Context, arg CreateAccountParams) (User, error) {
	row := q.queryRow(ctx, q.createAccountStmt, createAccount,
		arg.Username,
		arg.Email,
		arg.ProfilePicture,
		arg.Bio,
		arg.Role,
		arg.LastActivityAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.ProfilePicture,
		&i.Bio,
		&i.Role,
		&i.LastActivityAt,
		&i.CreatedAt,
	)
	return i, err
}
