// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: user.sql

package db

import (
	"context"
	"database/sql"
	"time"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
username,
email,
password,
profile_picture,
bio,
role,
last_activity_at
) VALUES (
$1, $2, $3, $4, $5, $6, $7
) RETURNING id, username, email, password, following_count, followed_count, bio, role, profile_picture, created_at, last_activity_at
`

type CreateUserParams struct {
	Username       sql.NullString `json:"username"`
	Email          string         `json:"email"`
	Password       string         `json:"password"`
	ProfilePicture sql.NullString `json:"profile_picture"`
	Bio            sql.NullString `json:"bio"`
	Role           string         `json:"role"`
	LastActivityAt time.Time      `json:"last_activity_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.queryRow(ctx, q.createUserStmt, createUser,
		arg.Username,
		arg.Email,
		arg.Password,
		arg.ProfilePicture,
		arg.Bio,
		arg.Role,
		arg.LastActivityAt,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FollowingCount,
		&i.FollowedCount,
		&i.Bio,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id int32) error {
	_, err := q.exec(ctx, q.deleteUserStmt, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, username, email, password, following_count, followed_count, bio, role, profile_picture, created_at, last_activity_at FROM users
WHERE id = $1 LIMIT 1
`

func (q *Queries) GetUser(ctx context.Context, id int32) (User, error) {
	row := q.queryRow(ctx, q.getUserStmt, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FollowingCount,
		&i.FollowedCount,
		&i.Bio,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, username, email, password, following_count, followed_count, bio, role, profile_picture, created_at, last_activity_at FROM users WHERE email = $1 LIMIT 1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.queryRow(ctx, q.getUserByEmailStmt, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FollowingCount,
		&i.FollowedCount,
		&i.Bio,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
SELECT id, username, email, password, following_count, followed_count, bio, role, profile_picture, created_at, last_activity_at FROM users WHERE username = $1 LIMIT 1
`

func (q *Queries) GetUserByUsername(ctx context.Context, username sql.NullString) (User, error) {
	row := q.queryRow(ctx, q.getUserByUsernameStmt, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FollowingCount,
		&i.FollowedCount,
		&i.Bio,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}

const getUsers = `-- name: GetUsers :many
SELECT id, username, email, password, following_count, followed_count, bio, role, profile_picture, created_at, last_activity_at FROM users
LIMIT $1 OFFSET $2
`

type GetUsersParams struct {
	Limit  int32 `json:"limit"`
	Offset int32 `json:"offset"`
}

func (q *Queries) GetUsers(ctx context.Context, arg GetUsersParams) ([]User, error) {
	rows, err := q.query(ctx, q.getUsersStmt, getUsers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Username,
			&i.Email,
			&i.Password,
			&i.FollowingCount,
			&i.FollowedCount,
			&i.Bio,
			&i.Role,
			&i.ProfilePicture,
			&i.CreatedAt,
			&i.LastActivityAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
username = $2,
email = $3,
profile_picture = $4,
bio = $5
WHERE id = $1
RETURNING id, username, email, password, following_count, followed_count, bio, role, profile_picture, created_at, last_activity_at
`

type UpdateUserParams struct {
	ID             int32          `json:"id"`
	Username       sql.NullString `json:"username"`
	Email          string         `json:"email"`
	ProfilePicture sql.NullString `json:"profile_picture"`
	Bio            sql.NullString `json:"bio"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.queryRow(ctx, q.updateUserStmt, updateUser,
		arg.ID,
		arg.Username,
		arg.Email,
		arg.ProfilePicture,
		arg.Bio,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Username,
		&i.Email,
		&i.Password,
		&i.FollowingCount,
		&i.FollowedCount,
		&i.Bio,
		&i.Role,
		&i.ProfilePicture,
		&i.CreatedAt,
		&i.LastActivityAt,
	)
	return i, err
}
